version: 2.1
jobs:
  job-1-centos:
    docker:
      - image: centos:latest
    steps:
      - checkout
      - run:
          name: "check if os is ok"
          command: "uname -a"
      - run:
          name: "install updates"
          command: "yum check-update && yum -y update && yum -y upgrade&& yum install sudo -y"
      - run:
          name: "install gcc & cmake "
          command: "sudo dnf group install "Development Tools""
  job-2-ubuntu:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: "check if os is ok"
          command: "uname -a"
      - run:
          name: "install updates"
          command: ""apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*""
  job-3-debian:
    docker:
      - image: debian:latest
    steps:
      - checkout
      - run:
          name: "check if os is ok"
          command: "uname -a"
      - run:
          name: "install updates"
          command: ""apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*""

workflows:
  version: 2.1
  pipelines: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - job-1-centos
      - job-2-ubuntu
      - job-3-debian