version: 2.1
jobs:
  job-1-centos:
    docker:
      - image: centos:latest
    steps:
      - checkout
      - run:
          name: "check if os is ok"
          command: "uname -a"
      # - run:
      #     name: "install updates"
      #     command: "yum -y update" ---->fails on official image
      - run:
          name: "install gcc & cmake "
          command: sudo dnf groupinstall -y "Development Tools" cmake
  job-2-ubuntu:
    docker:
      - image: ubuntu:latest
        environment:
          - TZ: Europe/Bucharest
          - DEBIAN_FRONTEND: noninteractive
    steps:
      - checkout
      - run:
          name: "check if os is ok"
          command: "uname -a"
      - run:
          name: "test if envar was properly initialized"
          command: "echo $DEBIAN_FRONTED"
      - run:
          name: "set env vars again"
          command: |
            echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
            echo 'export DEBIAN_FRONTEND=noninteractive >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: "install updates"
          command: "apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*"
      - run:
          name: "install gcc and cmake"
          command: "apt-get install -y tzdata&& apt-get install -y gcc  && apt-get install -y gcc"
  job-3-debian:
    docker:
      - image: debian:latest
    steps:
      - checkout
      - run:
          name: "check if os is ok"
          command: "uname -a"
      - run:
          name: "install updates"
          command: "apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*"

workflows:
  version: 2.1
  pipelines: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - job-1-centos
      - job-2-ubuntu
      # - job-3-debian
